### ISSUE TITLE
Peugeot 2008 Phase 1 vs Phase 2

### ISSUE THREAD

**Issue by kikosgc** [OBDb/Peugeot-2008#2]
Hi there,
I've noticed that the repo currently seems to cover the Peugeot 2008 without distinguishing between the two different "releases" or versions of this car: Phase I (2013-2019) and Phase II (2019 - Present). These versions have significant differences in terms of design, features, and specifications. It would be great if the repo could reflect these differences to avoid any confusion and ensure the information is accurate for both phases of the Peugeot 2008.

Could you please clarify how you'd prefer to handle this? Maybe having separate branches or sections for Phase 1 and Phase 2 could help keep things organized?
![image](https://github.com/user-attachments/assets/526592e7-4c47-409f-9e00-e2cffbc26daf)

**Comment by jverkoey** [comment]
Currently every repo is set up so that there's a `signalsets/v3/default.json` file in the signalsets directory. It's set up this way to allow for differentiation based on model year or other vehicle parameters in the future, so we could imagine there being a structure like this:

```
signalsets/
  v3/
    default.json
    2013-2019.json
```

Where the 2013-2019 filename would let Sidecar know determine that, for model years 2013-2019, it should use that json file instead of the default one.

What do you think? Still firming this up so am open to input / discussion.

**Comment by kikosgc** [comment]
It seems like a straightforward way to implement differentiation and would allow tools like Sidecar to easily select the right configuration based on model year or version.

Thanks for your work and time!
